apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pod-dashboard
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pod-dashboard-label
  template:
    metadata:
      name: pod-dashboard-template
      labels:
        app: pod-dashboard-label
    containers:
    - name: pod-dashboard-container
      image: godspeed95/devops:latest
      ports:
      - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /heathz
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
      resources:
        requests:
          cpu: "300m"
          memory: "300Mi"
        limits:
          cpu: "400m"
          memory: "400Mi" 
